updated cross-spawn
aws-github-ops/aws-issue-triage-manager pull request #36
Opened 2024-11-21 00:36 UTC by khushail

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

2024-12-03 18:08 UTC, ashishdhingra requested changes
Running `npm ls cross-spawn` (after running `npm install`) shows below dependency tree:
```
aws-issue-triage-manager@1.0.0 /Users/<<USERNAME>>/source/GitHub/aws-github-ops/aws-issue-triage-manager
└─┬ gts@3.1.1
  ├─┬ eslint@7.32.0
  │ └── cross-spawn@7.0.3
  └─┬ execa@5.1.1
    └── cross-spawn@7.0.3
```
Please update `gts` to appropriate version (most likely latest version) that brings `cross-spawn@7.0.6`. You should then include both `package.json` and `package-lock.json` in your PR.

2024-12-05 01:00 UTC, khushail commented
> Running `npm ls cross-spawn` (after running `npm install`) shows below dependency tree:
> 
> ```
> aws-issue-triage-manager@1.0.0 /Users/<<USERNAME>>/source/GitHub/aws-github-ops/aws-issue-triage-manager
> └─┬ gts@3.1.1
>   ├─┬ eslint@7.32.0
>   │ └── cross-spawn@7.0.3
>   └─┬ execa@5.1.1
>     └── cross-spawn@7.0.3
> ```
> 
> Please update `gts` to appropriate version (most likely latest version) that brings `cross-spawn@7.0.6`. You should then include both `package.json` and `package-lock.json` in your PR.

khushail@a07817b31bf3 aws-issue-triage-manager % npm ls cross-spawn
aws-issue-triage-manager@1.0.0 /Users/khushail/ticket_issueTriageManager/aws-issue-triage-manager
└─┬ gts@5.3.1
  ├─┬ eslint@8.57.0
  │ └── cross-spawn@7.0.6
  └─┬ execa@5.1.1
    └── cross-spawn@7.0.6 deduped

2024-12-05 01:08 UTC, ashishdhingra approved these changes

2024-12-05 18:59 UTC, ashishdhingra approved these changes

2024-12-05 19:03 UTC, kellertk approved these changes

2024-12-05 19:28 UTC, merged